# Altas de la versión 2.2.0. Cada afirmación sale de las fuentes citadas (texto revisado el 04-10-2026):
#  - AESAN, Alimentación segura durante el embarazo (2.ª ed., 2024)            → A
#  - AESAN, Evita la listeriosis: consejos prácticos para grupos de riesgo (2026) → L
#  - NHS, Foods to avoid in pregnancy (apoyo)                                  → N
#  - EFSA, Cafeína                                                             → E
# Las marcas (Mercadona/Hacendado, Lidl, Aldi, Carrefour, Eroski, Dia…) solo son ejemplos para encontrar el
# producto: la recomendación depende de cómo está hecho y conservado, que hay que comprobar en la etiqueta.
A = "AESAN — Alimentación segura durante el embarazo (2.ª ed., 2024): https://www.aesan.gob.es/dam/jcr:6f57a77f-541c-4c54-a124-543d65b1aaf1/alimentacion_segura_embarazo.pdf"
L = "AESAN — Evita la listeriosis: consejos prácticos para grupos de riesgo (2026): https://www.aesan.gob.es/dam/jcr:b8fc1e69-c7a5-4d6c-98c0-e3b9fec5c4d6/Folleto_LISTERIOSIS.pdf"
N = "NHS (Reino Unido, apoyo) — Foods to avoid in pregnancy: https://www.nhs.uk/pregnancy/keeping-well/foods-to-avoid/"
E = "EFSA — Cafeína (embarazo: hasta 200 mg/día de todas las fuentes): https://www.efsa.europa.eu/es/topics/topic/caffeine"
MARCA = "Las marcas citadas son solo ejemplos para encontrarlo: lo que cuenta es la etiqueta del envase que tienes delante."

def f(id, nombre, cat, estado, resumen, sinonimos, riesgos=(), condiciones=(), consejos=(), alternativas=(), fuente=(A,)):
    return dict(id=id, nombre=nombre, sinonimos=list(sinonimos), categoria=cat, estado=estado, resumen=resumen,
                riesgos=list(riesgos), condiciones=list(condiciones), consejos=list(consejos), alternativas=list(alternativas), fuente=list(fuente))

PREP = "Platos preparados y comida del súper"
NUEVOS = [
 # ---------------- Bebidas ----------------
 f("agua", "Agua (del grifo, mineral o con gas)", "Bebidas", "verde",
   "Es la mejor bebida en el embarazo. AESAN recomienda entre 2 y 2,5 litros de agua al día (8-10 vasos).",
   ["agua", "agua mineral", "agua mineral natural", "agua del grifo", "agua embotellada", "botella de agua", "agua con gas",
    "agua de manantial", "agua hacendado", "font vella", "lanjarón", "bezoya", "solán de cabras", "aquabona", "vichy catalán"],
   condiciones=["Parte del agua ya llega con los alimentos; los días de calor o si haces actividad física, bebe un poco más (AESAN)."],
   consejos=["Si te han pedido vigilar la sal, mira el sodio en la etiqueta de las aguas con gas: AESAN pide no pasar de 5 g de sal al día en total."],
   alternativas=["Infusiones permitidas (ver su ficha)", "Leche o bebidas lácteas pasteurizadas"]),
 f("isotonicas-aguas-sabor", "Bebidas isotónicas y aguas con sabor azucaradas", "Bebidas", "amarillo",
   "Son bebidas azucaradas: AESAN aconseja evitarlas y beber agua.",
   ["isotónica", "bebida isotónica", "aquarius", "powerade", "gatorade", "agua con sabor", "agua saborizada", "bebida deportiva", "limonada envasada"],
   riesgos=["azúcares añadidos"],
   condiciones=["Mejor la versión sin azúcar, y de forma puntual.", "Si lleva cafeína o guaraná, cuenta para el máximo de 200 mg al día (EFSA)."],
   alternativas=["Agua", "Agua con unas rodajas de limón o pepino lavados"], fuente=(A, E)),
 f("batidos-lacteos", "Batidos lácteos envasados (cacao, fresa, vainilla) y leche con cacao", "Bebidas", "verde",
   "Hechos con leche pasteurizada o UHT son aptos. Los de cacao llevan un poco de cafeína y bastante azúcar.",
   ["batido de chocolate", "batido de cacao", "batido de fresa", "batido de vainilla", "cacaolat", "puleva batido", "batido hacendado",
    "leche con cacao", "café con leche envasado", "café latte en lata", "nesquik", "batido de proteínas lácteo"],
   condiciones=["Leche pasteurizada o UHT (AESAN la propone como alternativa segura a la leche cruda).", "Una vez abierto, a la nevera y respeta lo que diga la etiqueta."],
   consejos=["El cacao y los cafés envasados suman cafeína al límite de 200 mg al día (EFSA).", "AESAN recomienda reducir los azúcares añadidos."],
   alternativas=["Leche con cacao preparada en casa"], fuente=(L, A, E)),
 f("zumos-pasteurizados", "Zumos y néctares pasteurizados (brik o botella)", "Bebidas", "verde",
   "Los zumos y néctares pasteurizados son la opción que AESAN propone en lugar de los zumos envasados sin pasteurizar.",
   ["zumo de brik", "zumo envasado", "zumo pasteurizado", "néctar", "néctar de melocotón", "zumo de piña en brik", "don simón",
    "zumo hacendado", "solevita", "zumo de tomate", "mosto"],
   riesgos=["azúcares"],
   condiciones=["En la etiqueta debe poner «pasteurizado» o estar en brik a temperatura ambiente."],
   consejos=["Aunque sean seguros, AESAN aconseja reducir las bebidas azucaradas: mejor fruta entera."],
   alternativas=["Fruta entera pelada o lavada", "Zumo recién exprimido en casa y bebido al momento"], fuente=(L, A)),
 f("zumo-maquina-super", "Zumo de naranja de máquina del súper («exprímelo tú»)", "Bebidas", "rojo",
   "AESAN pide evitar los zumos envasados sin pasteurizar, incluidos los que preparas y envasas tú mismo en la tienda.",
   ["zumo de máquina", "zumo exprimido en el súper", "zumo de naranja de máquina", "exprimidora del supermercado", "zumo mercadona exprimido",
    "zumo recién exprimido envasado", "zumo de naranja exprimido envasado"],
   riesgos=["listeria"],
   condiciones=["En casa, exprimido en el momento y bebido enseguida, sí (AESAN)."],
   consejos=["No prepares zumo con antelación ni lo guardes para luego (AESAN)."],
   alternativas=["Zumo pasteurizado", "Naranja entera"], fuente=(L, A)),
 f("complementos", "Complementos alimenticios (vitaminas, proteína, quemagrasas, hierbas)", "Bebidas", "amarillo",
   "AESAN indica tomar solo los complementos alimenticios que te indique tu médica o médico.",
   ["complementos alimenticios", "suplementos", "multivitamínico", "vitaminas", "proteína en polvo", "batido de proteínas", "quemagrasas",
    "omega 3 en cápsulas", "colágeno", "melatonina", "spirulina", "espirulina"],
   riesgos=["vitamina A", "cafeína"],
   condiciones=["Solo los que te indique tu médica o médico (AESAN).", "Si llevan cafeína o guaraná, cuentan para los 200 mg al día (EFSA)."],
   consejos=["Lleva el envase a la consulta para que lo revisen.", "Los de hígado de pescado aportan vitamina A: AESAN fija un máximo de 3000 µg al día, también en el embarazo."],
   fuente=(A, E, N, "AESAN — Niveles máximos de ingesta admisible (vitamina A 3000 µg/día, incl. embarazadas; EFSA 2024): https://www.aesan.gob.es/dam/jcr:4165bdd3-c29b-4688-907f-b4b130cca3ae/Niveles%20m%C3%A1ximos%20de%20ingesta%20admisible.pdf")),
 # ---------------- Carnes y platos ----------------
 f("pollo-asado-super", "Pollo asado de supermercado o asador", PREP, "amarillo",
   "Recién hecho y caliente es apto. Si no lo comes enseguida, a la nevera y recaliéntalo bien.",
   ["pollo asado mercadona", "pollo asado de supermercado", "pollo a l'ast", "pollo del asador", "pollo al ast", "pollo rustido"],
   riesgos=["listeria si se enfría y se guarda mal"],
   condiciones=["AESAN: los platos listos para consumir calientes (por ejemplo, pollo asado) se comen lo antes posible; si no, refrigerados y recalentados a 70 ºC al menos 2 minutos.",
                "Que no tenga zonas rosadas ni jugos con sangre (NHS)."],
   consejos=["Las sobras no deben estar más de 2 horas a temperatura ambiente (AESAN)."], fuente=(L, A, N)),
 f("croquetas", "Croquetas (de jamón, pollo, bacalao…), caseras o congeladas", PREP, "verde",
   "Aptas si están bien calientes por dentro: AESAN pone las croquetas como ejemplo de cocinado válido incluso para el jamón curado.",
   ["croquetas", "croquetas de jamón", "croquetas de pollo", "croquetas de bacalao", "croquetas de cocido", "croquetas congeladas",
    "croquetas la cocinera", "croquetas hacendado", "croquetas de boletus", "bechamel"],
   condiciones=["Más de 70 ºC durante 2 minutos en el centro (AESAN). Las congeladas, según el tiempo de la etiqueta."],
   consejos=["AESAN aconseja preparaciones como horno o plancha y evitar el consumo de fritos: mejor de vez en cuando."],
   alternativas=["Croquetas al horno o en freidora de aire"], fuente=(A, L)),
 f("morcilla", "Morcilla (de Burgos, de cebolla, de arroz)", "Carnes y embutidos", "verde",
   "Bien cocinada (frita, a la plancha o en guiso) y caliente es apta.",
   ["morcilla", "morcilla de burgos", "morcilla de arroz", "morcilla de cebolla", "morcilla asturiana", "botifarra negra", "black pudding"],
   condiciones=["Cocinada hasta que esté muy caliente en el centro, sin partes crudas (NHS; AESAN: más de 70 ºC, 2 minutos)."],
   consejos=["Lleva bastante sal y grasa: AESAN pide moderar la sal (menos de 5 g al día)."], fuente=(N, A)),
 f("salchichas-frescas", "Salchichas frescas, chistorra, longaniza y butifarra (para cocinar)", "Carnes y embutidos", "verde",
   "Son carne cruda para cocinar: bien hechas por dentro son aptas.",
   ["salchichas frescas", "chistorra", "longaniza", "butifarra", "salchicha de pollo", "salchichas de cerdo frescas", "salchicha parrillera",
    "criollo", "chorizo criollo", "chorizo fresco", "chorizo para cocinar"],
   riesgos=["toxoplasma y bacterias si quedan crudas"],
   condiciones=["Sin tonos rosados en el centro (más de 70 ºC durante 2 minutos; AESAN, NHS)."],
   consejos=["Pínchalas o ábrelas para comprobar el centro."], fuente=(A, N)),
 f("conejo-codorniz", "Conejo, codorniz y otras aves de granja cocinadas", "Carnes y embutidos", "verde",
   "Bien cocinados son aptos. Si proceden de caza silvestre, mira la ficha de carne de caza.",
   ["conejo", "conejo al ajillo", "magret de pato", "confit de pato", "codorniz", "codornices", "pintada", "pichón"],
   condiciones=["Bien cocinados, sin restos rosados ni sangre (NHS; AESAN: más de 70 ºC, 2 minutos).",
                "El magret se suele servir poco hecho: pídelo bien hecho."],
   alternativas=["Pollo o pavo"], fuente=(A, N)),
 f("guisos-con-embutido", "Guisos y potajes con embutido (cocido, fabada, lentejas con chorizo…)", PREP, "verde",
   "El embutido curado cocinado a más de 70 ºC (2 minutos) se puede tomar: los guisos caseros calientes son aptos.",
   ["cocido madrileño", "fabada asturiana", "lentejas con chorizo", "callos", "pote gallego", "olla podrida",
    "escudella", "potaje", "fabada litoral", "cocido hacendado"],
   condiciones=["Bien caliente, recién hecho o recalentado hasta que humee (AESAN)."],
   consejos=["Las sobras, a la nevera en menos de 2 horas y en recipiente cerrado (AESAN).", "Lleva bastante sal: AESAN pide no pasar de 5 g al día."],
   fuente=(A, L)),
 f("platos-preparados-calentar", "Platos preparados para calentar (lasaña, canelones, arroces, pasta)", PREP, "amarillo",
   "Aptos si los calientas como dice la etiqueta, hasta que estén muy calientes en el centro. No los comas fríos.",
   ["lasaña", "lasaña congelada", "canelones", "plato preparado", "comida preparada", "tupper del súper", "arroz preparado", "pasta preparada",
    "plato precocinado", "precocinado", "lasaña hacendado", "plato preparado lidl", "plato preparado carrefour", "musaka", "moussaka"],
   riesgos=["listeria si se toman fríos"],
   condiciones=["AESAN: sigue las instrucciones de la etiqueta para calentarlos; más de 70 ºC durante 2 minutos.",
                "En el microondas, remueve para que el calor sea uniforme hasta que salga vapor (AESAN)."],
   consejos=[MARCA], fuente=(A, L)),
 f("tortilla-envasada", "Tortilla de patatas envasada (refrigerada)", PREP, "amarillo",
   "Fría, directamente del envase, entra en los alimentos listos para comer con huevo que AESAN pide evitar. Bien calentada, sí.",
   ["tortilla envasada", "tortilla de patatas envasada", "tortilla hacendado", "tortilla de supermercado", "tortilla refrigerada",
    "tortilla palacios", "tortilla de bar", "pincho de tortilla"],
   riesgos=["listeria", "salmonela si está poco cuajada"],
   condiciones=["Calentada hasta que humee en el centro (más de 70 ºC, 2 minutos; AESAN).", "En bar o restaurante: solo si está bien cuajada y caliente (AESAN pide evitar las tortillas poco cuajadas)."],
   consejos=[MARCA], alternativas=["Tortilla casera bien cuajada"], fuente=(A, L)),
 f("ensaladilla-rusa", "Ensaladilla rusa", PREP, "amarillo",
   "Hecha en casa con mayonesa comercial y comida pronto, sí. La envasada lista para comer o la de bar, mejor evitarla.",
   ["ensaladilla", "ensaladilla rusa", "ensalada rusa", "ensaladilla de cangrejo", "ensaladilla envasada", "ensaladilla de bar", "ensaladilla hacendado"],
   riesgos=["listeria", "salmonela si la mayonesa es casera"],
   condiciones=["En casa: patata, zanahoria y huevo bien cocidos; atún en lata; mayonesa comercial (huevo pasteurizado). A la nevera y pronto (AESAN).",
                "AESAN pide evitar los alimentos envasados listos para consumir con huevo, pescado o vegetales y las ensaladas consumidas fuera de casa."],
   consejos=[MARCA], alternativas=["Patata cocida aliñada con aceite y atún en lata"], fuente=(A, L)),
 f("hummus-untables", "Hummus envasado, guacamole y otros untables refrigerados", PREP, "amarillo",
   "Son alimentos listos para comer que se guardan en frío: respeta la fecha y la conservación de la etiqueta.",
   ["hummus envasado", "hummus hacendado", "hummus de supermercado", "guacamole", "guacamole envasado", "baba ganoush", "tzatziki", "paté vegetal", "untable de verduras",
    "crema de berenjena", "mutabal"],
   riesgos=["listeria (alimentos refrigerados listos para comer)"],
   condiciones=["AESAN: «Respeta las indicaciones de la etiqueta sobre conservación, uso y fechas». Nevera a 5 ºC o menos.",
                "El tzatziki y similares llevan yogur: que sea pasteurizado."],
   consejos=["Hecho en casa con garbanzos cocidos o de bote y comido en poco tiempo es la opción más tranquila.", MARCA],
   fuente=(L, A)),
 f("gazpacho-envasado", "Gazpacho y salmorejo envasados", PREP, "amarillo",
   "Mejor los que indican «pasteurizado» o los de brik a temperatura ambiente. El casero, con verduras bien lavadas, también.",
   ["gazpacho envasado", "gazpacho de brik", "gazpacho alvalle", "gazpacho hacendado", "salmorejo envasado", "salmorejo hacendado",
    "gazpacho don simón", "gazpacho refrigerado", "ajoblanco"],
   riesgos=["listeria si no está pasteurizado"],
   condiciones=["Igual que con los zumos, AESAN pide que los envasados estén pasteurizados.", "Respeta fecha y conservación; una vez abierto, a la nevera (AESAN)."],
   consejos=["Si el salmorejo casero lleva huevo duro, que esté bien cocido.", MARCA], fuente=(L, A)),
 # ---------------- Pescados y mariscos ----------------
 f("ahumado-conserva", "Pescado ahumado en conserva (lata, no refrigerado)", "Pescados", "verde",
   "AESAN propone el pescado ahumado en conserva como alternativa al ahumado refrigerado.",
   ["ahumado en lata", "sardinas ahumadas en lata", "mejillones ahumados en lata", "caballa ahumada en lata", "salmón ahumado en lata", "arenques ahumados en lata"],
   condiciones=["Conserva estable a temperatura ambiente; los que se venden en la nevera no valen (AESAN)."],
   alternativas=["Salmón ahumado cocinado en un plato caliente"], fuente=(L,)),
 f("huevas-caviar", "Huevas de pescado y caviar", "Pescados", "amarillo",
   "Cocidas (hueva de merluza cocida, por ejemplo), sí. Crudas, curadas o de nevera (caviar, huevas de salmón o de trucha), mejor evitarlas.",
   ["huevas", "hueva de merluza", "huevas de merluza", "caviar", "sucedáneo de caviar", "huevas de salmón", "huevas de trucha", "huevas de lumpo", "botarga", "hueva de mújol"],
   riesgos=["listeria"],
   condiciones=["Bien cocinadas (AESAN: pescado bien hecho, sin zonas crudas).", "AESAN pide evitar el pescado crudo, marinado o ahumado refrigerado; el NHS, el pescado curado sin cocinar."],
   fuente=(A, L, N)),
 f("pescado-empanado", "Pescado empanado y varitas congeladas", PREP, "verde",
   "Aptos si se cocinan según la etiqueta hasta estar bien calientes por dentro.",
   ["varitas de merluza", "palitos de pescado", "pescado empanado", "rebozado de merluza", "pescanova", "findus", "san jacobo de pescado",
    "nuggets de pescado", "calamares a la romana congelados", "rabas congeladas"],
   condiciones=["Sigue tiempo y temperatura de la etiqueta (AESAN); sin zonas crudas o translúcidas por dentro."],
   consejos=["Mejor al horno que fritos (AESAN aconseja evitar los fritos)."], fuente=(A, L)),
 f("marisco-crudo", "Erizos de mar, tartar y carpaccio de marisco crudo", "Mariscos", "rojo",
   "El marisco crudo puede llevar bacterias, virus o toxinas: en el embarazo, mejor evitarlo.",
   ["erizos", "erizo de mar", "tartar de gambas", "carpaccio de gambas", "carpaccio de vieira", "vieiras crudas", "almejas crudas",
    "navajas crudas", "ceviche de marisco", "gambas crudas"],
   riesgos=["listeria", "norovirus", "toxinas"],
   condiciones=["AESAN pide evitar los mariscos crudos o parcialmente cocidos; el NHS, el marisco crudo."],
   alternativas=["Marisco bien cocinado (gambas a la plancha, vieiras gratinadas)", "Mejillones en escabeche en conserva"], fuente=(A, L, N)),
 # ---------------- Frutas, verduras ----------------
 f("fruta-pelada", "Fruta que se pela (plátano, naranja, mandarina, kiwi, aguacate…)", "Frutas, verduras y vegetales", "verde",
   "AESAN propone la fruta fresca pelada como opción segura frente a la listeria.",
   ["plátano", "banana", "naranja", "mandarina", "kiwi", "aguacate", "granada", "lichi", "pomelo", "piña natural", "chirimoya", "nísperos"],
   condiciones=["Lávate las manos y pélala en el momento. AESAN pide lavar también el exterior de los melones y otras frutas que no se pelan."],
   consejos=["AESAN recomienda al menos 5 raciones de frutas y hortalizas al día."], fuente=(L, A)),
 f("compotas-conservas-fruta", "Compotas, fruta en almíbar y bolsitas de fruta triturada", "Frutas, verduras y vegetales", "verde",
   "AESAN las propone como alternativa segura: fruta cocida, en conserva o pasteurizada.",
   ["compota", "compota de manzana", "fruta en almíbar", "melocotón en almíbar", "piña en lata", "macedonia en lata", "bolsita de fruta",
    "pouch de fruta", "puré de fruta", "fruta triturada", "manzana asada"],
   riesgos=["azúcar en el almíbar"],
   consejos=["Mejor «al natural» o en su jugo que en almíbar (AESAN pide reducir azúcares)."], fuente=(L, A)),
 f("verduras-cocinadas", "Verduras cocinadas (hervidas, al vapor, al horno, salteadas)", "Frutas, verduras y vegetales", "verde",
   "Cocinadas son de lo más seguro y recomendable.",
   ["verduras cocidas", "verdura hervida", "verduras al vapor", "verduras al horno", "verduras salteadas", "brócoli", "judías verdes",
    "coliflor", "calabacín", "berenjena", "pisto", "crema de verduras", "puré de verduras", "alcachofas", "champiñones", "setas", "espinacas cocidas", "acelgas"],
   condiciones=["Sin condiciones especiales. Las sobras, a la nevera y recalentadas a más de 70 ºC (AESAN)."],
   consejos=["AESAN recomienda cocción, vapor o plancha y al menos 5 raciones de frutas y hortalizas al día."], fuente=(L, A)),
 f("verduras-conserva", "Hortalizas en conserva (menestra, pimientos asados, espárragos, guisantes)", "Frutas, verduras y vegetales", "verde",
   "AESAN las propone como alternativa segura a la verdura cruda.",
   ["menestra", "pimientos asados", "pimientos del piquillo", "espárragos en lata", "espárragos blancos", "guisantes en lata", "maíz dulce",
    "alcachofas en conserva", "tomate triturado", "pisto en lata", "judías verdes en conserva", "palmitos"],
   condiciones=["Lata o bote sin abombar ni golpes; una vez abiertos, a la nevera en recipiente cerrado."],
   consejos=["Algunas conservas llevan bastante sal: AESAN pide no pasar de 5 g al día. Enjuágalas si puedes."], fuente=(L, A)),
 f("snacks-salados", "Snacks salados (patatas fritas de bolsa, gusanitos, palomitas, frutos secos fritos)", "Cereales, legumbres y otros", "amarillo",
   "No tienen riesgo infeccioso, pero llevan mucha sal y grasa: AESAN pide moderar la sal y evitar los fritos.",
   ["patatas fritas", "patatas de bolsa", "chips", "gusanitos", "palomitas", "nachos", "doritos", "pipas", "cortezas", "kikos", "snacks", "aperitivos", "lays", "risketos"],
   riesgos=["sal", "grasas"],
   condiciones=["Ocasionalmente y en poca cantidad. Menos de 5 g de sal al día en total (AESAN)."],
   alternativas=["Frutos secos naturales o tostados sin sal", "Palomitas caseras con poca sal"], fuente=(A,)),
 # ---------------- Cereales y otros ----------------
 f("pan-cereales", "Pan, tostadas, cereales de desayuno y avena", "Cereales, legumbres y otros", "verde",
   "Aptos. AESAN recomienda que los cereales sean, preferiblemente, integrales.",
   ["pan", "pan integral", "barra de pan", "pan de molde", "tostadas", "biscotes", "cereales", "cereales de desayuno", "avena", "copos de avena",
    "muesli", "granola", "porridge", "picos", "regañás", "pan bimbo"],
   consejos=["Elige integrales y con poco azúcar y sal (mira la etiqueta)."], fuente=(A,)),
 f("pasta", "Pasta (macarrones, espaguetis, fideos…)", "Cereales, legumbres y otros", "verde",
   "Apta. Las salsas son las que pueden necesitar cuidado (carbonara con huevo crudo, quesos sin pasteurizar).",
   ["pasta", "macarrones", "espaguetis", "spaghetti", "fideos", "tallarines", "fideuá", "ñoquis", "tortellini", "raviolis", "pasta fresca rellena"],
   condiciones=["La pasta fresca rellena (refrigerada), bien cocida y caliente.", "Salsas con huevo, solo si este queda bien cuajado o es pasteurizado (AESAN)."],
   fuente=(A, L)),
 f("quinoa-cuscus", "Quinoa, cuscús, bulgur y otros cereales", "Cereales, legumbres y otros", "verde",
   "Aptos y útiles para variar cereales.",
   ["quinoa", "quinua", "cuscús", "cous cous", "bulgur", "trigo sarraceno", "mijo", "espelta", "teff", "amaranto", "polenta"],
   condiciones=["Cocinados y, si sobran, a la nevera pronto y recalentados (AESAN)."],
   consejos=["Ensaladas de cuscús o quinoa: en casa, con verduras lavadas o cocidas."], fuente=(A,)),
 f("proteina-vegetal", "Seitán y «carne vegetal» (hamburguesas vegetales, Heura…)", "Cereales, legumbres y otros", "verde",
   "Aptos si se cocinan o calientan como indica la etiqueta.",
   ["seitán", "heura", "carne vegetal", "hamburguesa vegetal", "burger vegana", "salchicha vegana", "nuggets veganos", "proteína de guisante", "soja texturizada"],
   condiciones=["Sigue las instrucciones de cocinado o calentado de la etiqueta (AESAN)."],
   consejos=["La soja tiene su propia ficha.", MARCA], fuente=(A,)),
 f("sal-salsas", "Sal, caldos en pastilla y salsas saladas (soja, kétchup…)", "Cereales, legumbres y otros", "amarillo",
   "AESAN pide no superar los 5 g de sal al día, contando la de los alimentos que compras.",
   ["sal", "pastilla de caldo", "avecrem", "caldo de brik", "kétchup", "ketchup", "mostaza", "salsa barbacoa", "salsa brava", "tabasco"],
   riesgos=["sal"],
   condiciones=["Menos de 5 g de sal al día en total (AESAN). Revisa la sal en el etiquetado."],
   consejos=["Usa hierbas aromáticas (lavadas), limón o especias para dar sabor.", "Las salsas comerciales envasadas son aptas por el huevo (ver su ficha); lo que hay que vigilar es la sal."],
   fuente=(A,)),
 # ---------------- Huevos y dulces ----------------
 f("huevos-otras-aves", "Huevos de codorniz, pato y oca", "Huevos y postres", "amarillo",
   "Solo bien cocinados: el NHS desaconseja tomarlos crudos o poco hechos.",
   ["huevo de codorniz", "huevos de codorniz", "huevo de pato", "huevos de pato", "huevo de oca"],
   riesgos=["salmonela"],
   condiciones=["Clara y yema bien cuajadas (NHS; AESAN: huevos cocidos o bien cuajados)."], fuente=(N, L)),
 f("pasteleria", "Pasteles, bollería y postres de pastelería (con crema, nata o merengue)", "Huevos y postres", "amarillo",
   "Los industriales o hechos con huevo pasteurizado o con tratamiento térmico son aptos. Los caseros con huevo crudo, no.",
   ["pasteles", "pastel", "bollería", "bollos", "croissant", "napolitana", "donut", "magdalenas", "galletas", "palmera",
    "ensaimada", "pastel de nata", "tarta de queso", "tarta", "pastelería", "milhojas", "lionesas", "petisús"],
   riesgos=["huevo crudo (merengue o cremas caseras)", "azúcar"],
   condiciones=["AESAN: postres y pastelería con huevo pasteurizado o sometidos a más de 70 ºC durante 2 minutos.",
                "Evita merengues y pasteles caseros con huevo crudo (AESAN)."],
   consejos=["Rellenos de nata o crema: siempre refrigerados. AESAN pide reducir azúcares y grasas."], fuente=(L, A)),
 f("dulces-navidad", "Turrón, polvorones, mazapán y dulces de Navidad", "Dulces y endulzantes", "verde",
   "Los industriales envasados son aptos con moderación por el azúcar.",
   ["turrón", "turrón de jijona", "turrón de alicante", "turrón de chocolate", "polvorones", "mantecados", "mazapán", "roscón de reyes",
    "roscón", "panettone", "peladillas", "marquesas"],
   riesgos=["azúcar"],
   condiciones=["El roscón con nata o trufa, siempre refrigerado (como la pastelería con nata)."],
   consejos=["AESAN pide reducir los productos con azúcares añadidos. Los licores en dulces (bombones de licor, borrachos) cuentan como alcohol: evítalos."],
   fuente=(A,)),
]
